### ISSUE TITLE
Vite throws 'Uncaught ReferenceError: regeneratorRuntime is not defined'

### ISSUE THREAD

**Issue by dd-jonas** [TanStack/react-location#227]
**Describe the bug**
Uncaught ReferenceError: regeneratorRuntime is not defined when using react-location with Vite.

**To Reproduce**
1. `yarn create vite --template react-ts`
2. `yarn`
3. `yarn add @tanstack/react-location`
4. Replace `App.tsx` with code below
5. `yarn dev`

```tsx
import { ReactLocation, Router } from '@tanstack/react-location';

const location = new ReactLocation();

function App() {
  return (
    <Router location={location} routes={[{ path: '/' }]}>
      <h1>Title</h1>
    </Router>
  );
}

export default App;
```

**Screenshots**
![Console error](https://i.imgur.com/PeEu9Ul.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 64-bits
 - Browser: Chrome
 - Version: 98.0.4758.102

**Comment by danielbayerlein** [comment]
See #220. Should be fixed with #223.

**Comment by ruisaraiva19** [comment]
This still happens with version 3.6.5 which has #223.

Dependencies
- Vite: 2.8.6
- @tanstack/react-location: 3.6.5

Only works when using version `react-location` <= 3.3.5

**Comment by danielbayerlein** [comment]
The problem still exists with version 3.7.0.

**Comment by hugobdev** [comment]
Issues are not related. To fix this one you will have to use the `regenerator-runtime` library and call it from your main file. 

See this discussion on a similar issue with `amplify-js` https://github.com/aws-amplify/amplify-js/issues/8514#issuecomment-871904042

Here, I solved it by installing `regenerator-runtime` (`yarn add regenerator-runtime`) and adding `import 'regenerator-runtime'` to the top-level JavaScript file in my application (`main.tsx` in my case).

**Comment by ruisaraiva19** [comment]
@hugobdev that's for the suggestion. Importing `regenerator-runtime` fixes the issue.

Maybe this is something that can be added to the docs.

**Comment by dd-jonas** [comment]
I have tried out react-location a while back with vite and didn't encounter this issue. What changes that made importing `regenerator-runtime` necessary now?

**Comment by bhbs** [comment]
This issue was fixed with #236 
Try the latest version 👍 v3.7.2

**Comment by reintroducing** [comment]
Still happening for me in v3.7.4. 
![Screen Shot 2022-04-28 at 1 48 25 PM](https://user-images.githubusercontent.com/259901/165843074-dac545dc-d730-46be-b8c5-a1bef3ddbc25.png)

**Comment by unional** [comment]
Still happening in vite 4.0.2

**Comment by elmapaul** [comment]
Still happening in vite 4.3.9

**Comment by fruitbang** [comment]
It is still there! vite 4.4.0

**Comment by datnguyennnx** [comment]
Try this way: 
`pnpm install vite-plugin-babel`

Then copy this code to vite.config.ts

**Comment by vishal4kingsbridge** [comment]
When using React Table, if your code uses async/await syntax, you need to introduce the regenerator-runtime library into the project.

1. You can install the regenerator-runtime library via npm and then include it in your code:
npm install --save regenerator-runtime

2. Introduce it in your entry file, such as index.js or main.js
import 'regenerator-runtime/runtime'
